services:
  - type: web
    name: bloodbank-api
    env: node
    buildCommand: yarn install --update-lockfile
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: BLOODBANK
      - key: JWT_SECRET
        sync: false